#ifndef _SETTINGS_H_
#define _SETTINGS_H_


#define LED_MATRIX_WIDTH  16
#define LED_MATRIX_HEIGHT 16
#define LED_MATRIX_DEPTH  3
#define NUM_LEDS ( LED_MATRIX_WIDTH * LED_MATRIX_HEIGHT )

int bitmap[NUM_LEDS*LED_MATRIX_DEPTH];

#endif // _SETTINGS_H_
